name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Prepare xcodeproj
      run: swift package generate-xcodeproj
    - name: Run tests
      run: xcodebuild test -scheme RestorableCountdown-Package -destination platform="macOS" -enableCodeCoverage YES -derivedDataPath .build/derivedData
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5